"""empty message

Revision ID: 27b98153a14d
Revises: e7d6f1810757
Create Date: 2022-08-02 00:02:22.356413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b98153a14d'
down_revision = 'e7d6f1810757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caimaneras', sa.Column('longitud', sa.String(length=120), nullable=False))
    op.add_column('caimaneras', sa.Column('latitud', sa.String(length=120), nullable=False))
    op.drop_column('caimaneras', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caimaneras', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('caimaneras', 'latitud')
    op.drop_column('caimaneras', 'longitud')
    # ### end Alembic commands ###
