"""empty message

Revision ID: 5eefbef89f78
Revises: 6a3ddd86c1f9
Create Date: 2022-07-29 00:27:22.648286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eefbef89f78'
down_revision = '6a3ddd86c1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('caimaneras_datetime_key', 'caimaneras', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('caimaneras_datetime_key', 'caimaneras', ['datetime'])
    # ### end Alembic commands ###
