"""empty message

Revision ID: e7d6f1810757
Revises: 5eefbef89f78
Create Date: 2022-07-31 14:35:17.141674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7d6f1810757'
down_revision = '5eefbef89f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caimaneras', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caimaneras', 'name')
    # ### end Alembic commands ###
